apiVersion: v1
kind: ConfigMap
metadata:
  name: globalmainpage
  namespace: default
data:
  index.html: |
    <html>
        <body>
            <h1>!!!Welcome to Royal Caribbean Cruise Liners!!!</h1>
            <img src="https://media4.giphy.com/media/UuYwihkHeDptzuEkrG/giphy.gif?cid=ecf05e47kx1ct8vf0c6nmlw9ybxsz0j0txahwb80xx722nwy&rid=giphy.gif&ct=g">
        </body>
    </html>
