apiVersion: v1
kind: ConfigMap
metadata:
  name: globalmainpage
  namespace: default
data:
  index.html: |
    <html>
        <body>
            <h1>!!!Welcome to INTUITIVE!!!</h1>
            <img src="https://officesnapshots.com/wp-content/uploads/2021/08/intuitive-surgical-offices-sunnyvale-1-700x467-compact.jpg">
            <h2>da Vinci</h2>
            <p><a href="ship.html">Please click here for details</a></p>
        </body>
    </html>
