apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  namespace: ${releaseNamespace}
  annotations:
    kubernetes.io/ingress.class: kommander-traefik
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: test
          servicePort: 80
        path: /index.html
        pathType: ImplementationSpecific
