apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: kommander-traefik
    traefik.ingress.kubernetes.io/router.middlewares: kommander-stripprefixes@kubernetescrd
    traefik.ingress.kubernetes.io/router.tls: "true"    
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: test
          servicePort: 80
        path: /hello
        pathType: ImplementationSpecific
