apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
spec:
  rules:
    - http:
        paths:
          - path: /index.html
            backend:
              service:
                name: test
                port:
                  number: 80
            pathType: ImplementationSpecific      
