apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    kubernetes.io/ingress.class: kommander-traefik  
spec:
  rules:
    - http:
        paths:
          - path: /index.html
            backend:
              serviceName: test
              servicePort: 80
