apiVersion: v1
kind: ConfigMap
metadata:
  name: globalmainpage
  namespace: default
data:
  index.html: |
    <html>
        <body>
            <h1>!!Welcome to The Portal!!</h1>
            <h2>The Portal</h2>
            <img src="https://www.cubstudio.com/visa">
        </body>
    </html>
