apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: shipwelcome
  namespace: {{ .Release.Namespace }}
spec:
  patches:
   - patch: |
       - op: replace
         path: /metadata/namespace
         value: {{ .Release.Namespace }}
     target:
       kind: Deployment
   - patch: |
       - op: replace
         path: /metadata/namespace
         value: {{ .Release.Namespace }}
     target:
       kind: Service
   - patch: |
       - op: replace
         path: /metadata/namespace
         value: {{ .Release.Namespace }}
     target:
       kind: ConfigMap
   - patch: |
       - op: replace
         path: /metadata/namespace
         value: {{ .Release.Namespace }}
     target:
       kind: Ingress
   - patch: |
       - op: replace
         path: /metadata/namespace
         value: {{ .Release.Namespace }}
     target:
       kind: Middleware
  postBuild:
    substitute:
      middleware: {{ .Release.Namespace }}-welcomeglobal-stripprefixes@kubernetescrd      
  interval: 5s
  path: ./ships/{{ .Values.shipname }}
  prune: true
  serviceAccountName: {{ .Release.Namespace }}
  sourceRef:
   kind: GitRepository
   name: demo-repo-ship
   namespace: {{ .Release.Namespace }}
