apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: shipwelcome
  namespace: ${releaseNamespace}
spec:
  patches:
   - patch: |
       - op: replace
         path: /metadata/namespace
         value: ${releaseNamespace}
     target:
       kind: Deployment
   - patch: |
       - op: replace
         path: /metadata/namespace
         value: ${releaseNamespace}
     target:
       kind: Service
   - patch: |
       - op: replace
         path: /metadata/namespace
         value: ${releaseNamespace}
     target:
       kind: ConfigMap
   - patch: |
       - op: replace
         path: /metadata/namespace
         value: ${releaseNamespace}
     target:
       kind: Ingress
   - patch: |
       - op: replace
         path: /metadata/namespace
         value: ${releaseNamespace}
     target:
       kind: Middleware
  postBuild:
    substitute:
      middleware: ${releaseNamespace}-welcomeglobal-stripprefixes@kubernetescrd      
  interval: 5s
  path: ./ships/{{ .Values.shipname }}
  prune: true
  serviceAccountName: ${releaseNamespace}
  sourceRef:
   kind: GitRepository
   name: demo-repo-ship
   namespace: ${releaseNamespace}
